server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2

  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password:
    driver-class-name: org.h2.Driver

jwt:
  header: Authorization
  secret: dhjkew8r32r875024u95u42t8gdhgkjdshg32095137rq0wyriosfh7
  expired-time: 86400